"""Materialize curated eval points on Modal, one container per session.

Local preparation is Whisper-bound (hours of context audio per session);
each container transcribes on a T4 next to S3, uploads its session's point
artifacts to s3://pmt-data-seamless/processed/ (mirroring data/processed/),
and the local entrypoint syncs them down and rebuilds the cross-source
manifest, which is uploaded too. The interact-only full-conversation pair
(user.wav / assistant.wav) is not uploaded: eval never reads it and it
dominates the dataset size.

Recall points are generated by default: the image ships qwen-tts so probe
synthesis works, and after the sync the entrypoint fails if any eval metric
ended up with zero points.

Run: uv run modal run data_processing/prepare_modal.py [--limit N]
Requires the pmt-aws and pmt-openai Modal secrets.
"""

from __future__ import annotations

import json
import shutil
import tempfile
from collections import Counter
from pathlib import Path

import boto3
import modal

from data_processing.curation import load_curation
from data_processing.prepare_eval import process_datapoint, update_root_manifest
from data_processing.source_common import download_s3_keys, list_s3_keys
from data_processing.source_seamless import SEAMLESS_BUCKET
from data_processing.sources import get_source

# Mirrors data/processed/ (history capped at HISTORY_CAP_SEC, no interact WAV
# pair, recall probes included). On a breaking artifact change, wipe the
# prefix and regenerate rather than mixing generations.
PROCESSED_PREFIX = "processed/"
DOWNLOAD_WORKERS = 24
INTERACT_ONLY_FILES = {"user.wav", "assistant.wav"}

# Every metric the prepared dataset feeds. A run that leaves any of these at
# zero points is misconfigured (e.g. TTS silently absent), not a result.
EXPECTED_SPLIT_TYPES = (
    "pause_start",
    "end_of_turn",
    "fact_recall",
    "conversation_recall",
)

app = modal.App("people-bench-prepare")

image = (
    modal.Image.debian_slim(python_version="3.11")
    .apt_install("ffmpeg", "sox")
    .pip_install(
        "numpy",
        "boto3",
        "matplotlib",
        "openai-whisper",
        "python-dotenv",
        "qwen-tts",
    )
    .add_local_python_source("data_processing", "bench", "utils", "env")
)


@app.function(
    image=image,
    gpu="T4",
    secrets=[
        modal.Secret.from_name("pmt-aws"),
        modal.Secret.from_name("pmt-openai"),
    ],
    # The longest sessions (~49 min of audio) put well over an hour of Whisper
    # work through one T4 across interact transcripts, capped histories, and
    # recall prefixes.
    timeout=3600,
    max_containers=64,
)
def prepare_session(datasource: str, source_name: str, curation: dict) -> dict:
    s3 = boto3.client("s3")
    source = get_source(datasource)
    with tempfile.TemporaryDirectory() as temp_dir:
        datapoint_dir = Path(temp_dir) / source_name.replace("-", "_")
        loaded = source.load(s3, source_name, datapoint_dir)
        output_root = Path(temp_dir) / "processed"
        process_datapoint(
            datapoint_dir,
            output_root,
            source_labels=loaded.source_labels,
            source_audio=loaded.source_audio,
            channel_words=loaded.channel_words,
            curation=curation,
        )
        source_dir = output_root / loaded.source_id
        uploaded = []
        for path in sorted(source_dir.rglob("*")):
            if not path.is_file() or path.name in INTERACT_ONLY_FILES:
                continue
            key = (
                f"{PROCESSED_PREFIX}{loaded.source_id}/"
                f"{path.relative_to(source_dir).as_posix()}"
            )
            s3.upload_file(str(path), SEAMLESS_BUCKET, key)
            uploaded.append(key)
        with (source_dir / "manifest.json").open(encoding="utf-8") as handle:
            point_paths = json.load(handle)["points"]
    return {
        "source_id": loaded.source_id,
        "points": point_paths,
        "uploaded": len(uploaded),
    }


def download_source(s3, source_id: str, output_root: Path) -> int:
    """Mirror one source's artifacts from S3, replacing any local copy."""
    source_dir = output_root / source_id
    if source_dir.exists():
        shutil.rmtree(source_dir)
    prefix = f"{PROCESSED_PREFIX}{source_id}/"
    keys = list_s3_keys(s3, SEAMLESS_BUCKET, prefix)
    download_s3_keys(
        s3,
        SEAMLESS_BUCKET,
        keys,
        source_dir,
        strip_prefix=prefix,
        workers=DOWNLOAD_WORKERS,
    )
    return len(keys)


@app.local_entrypoint()
def main(
    output_dir: str = "data/processed",
    curation_dir: str = "data/curation",
    datasource: str = "seamless",
    limit: int = 0,
    profile: str = "pmt",
    sources: str = "",
) -> None:
    output_root = Path(output_dir)
    curation_path = Path(curation_dir)
    source = get_source(datasource)
    s3 = boto3.Session(profile_name=profile).client("s3")
    selected = {name.strip() for name in sources.split(",") if name.strip()}

    arguments = []
    for source_name in source.list_names(s3):
        source_id = source_name.replace("-", "_")
        if selected and source_id not in selected:
            continue
        curation = load_curation(curation_path, source_id)
        if curation is None:
            raise FileNotFoundError(f"no curation decisions for {source_id}")
        # Sessions with zero kept split events still produce recall points.
        arguments.append((datasource, source_name, curation))
    if limit:
        arguments = arguments[:limit]
    print(f"Preparing {len(arguments)} curated {source.name} session(s) on Modal")

    output_root.mkdir(parents=True, exist_ok=True)
    total_points = 0
    for result in prepare_session.starmap(arguments):
        source_id = result["source_id"]
        files = download_source(s3, source_id, output_root)
        update_root_manifest(output_root, source_id, result["points"])
        total_points += len(result["points"])
        print(
            f"{source_id}: {len(result['points'])} points, "
            f"{files} files synced",
            flush=True,
        )
    counts = split_type_counts(output_root)
    print(f"Point counts by split type: {counts}")
    missing = [name for name in EXPECTED_SPLIT_TYPES if not counts.get(name)]
    if missing:
        raise RuntimeError(f"run produced no points for: {', '.join(missing)}")
    s3.upload_file(
        str(output_root / "manifest.json"),
        SEAMLESS_BUCKET,
        f"{PROCESSED_PREFIX}manifest.json",
    )
    print(
        f"Done. {total_points} eval points across {len(arguments)} session(s) "
        f"-> {output_root / 'manifest.json'}"
    )


def split_type_counts(output_root: Path) -> dict[str, int]:
    with (output_root / "manifest.json").open(encoding="utf-8") as handle:
        points = json.load(handle)["points"]
    counts: Counter[str] = Counter()
    for rel in points:
        with (output_root / rel).open(encoding="utf-8") as handle:
            counts[json.load(handle)["split_type"]] += 1
    return dict(counts)
